export const RECEIVE_SETRECIPES = 'RECEIVE_SETRECIPES'
export const RECEIVE_SETSEARCHTEXT = 'RECEIVE_SETSEARCHTEXT'
export const RECEIVE_SETSEARCHRESULT = 'RECEIVE_SETSEARCHRESULT'
export const RECEIVE_NEWRECIPE = 'RECEIVE_NEWRECIPE'
